# Generated by Django 3.0.5 on 2022-03-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_newpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
