# Generated by Django 3.0.5 on 2022-03-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220309_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unicode',
            field=models.CharField(default=None, max_length=36, null=True),
        ),
    ]
